name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: cron-wizard
  GKE_CLUSTER: cron-wizard-cluster
  GKE_ZONE: us-central1-a
  IMAGE: cron-wizard
  REGISTRY: us-central1-docker.pkg.dev
  REPOSITORY: cron-wizard-repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker ${{ env.REGISTRY }} --quiet

      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}

      - name: Install GKE auth plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }}
        env:
          USE_GKE_GCLOUD_AUTH_PLUGIN: "True"

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/${{ env.IMAGE }} ${{ env.IMAGE }}=${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}
        env:
          USE_GKE_GCLOUD_AUTH_PLUGIN: "True"

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/${{ env.IMAGE }} ${{ env.IMAGE }}=${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}